---
name: Python Style Check

on:
  - push
  - pull_request

env:
  black_version: 22.3.0
  flake8_version: 3.9.2
  python_version: '3.10'

jobs:
  run-black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install black==${{ env.black_version }}
      - name: Run Black
        run: black --check --diff .

  run-flake8:
    name: Flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install flake8==${{ env.flake8_version }}
      - name: Run Flake8
        run: flake8 --count --statistics --show-source --jobs=$(nproc) .
      - name: Run Flake8 on additional files
        run: |
          flake8 --count --statistics --show-source \
            --jobs=$(nproc) python/grass/{script,jupyter}/testsuite/
