---
name: Publish GRASS

on:
  release:
    types: [published]
env:
  OUT_DIR: ${{ github.workspace }}/.g_outdir
  GRASS: grass-${{ github.ref_name }}
permissions:
  contents: write
jobs:
  build-n-publish:
    name: Build and publish GRASS
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate Git derived data files
        run: |
          echo "Generate VERSION_GIT file:"
          ./utils/generate_version_git_file.sh
          cat include/VERSION_GIT
          echo "Generate GENERATE_LAST_COMMIT_FILE:"
          python utils/generate_last_commit_file.py .
          cat core_modules_with_last_commit.json
      - name: Create tarballs
        run: |
          mkdir ${{ env.OUT_DIR }}
          cd ..
          tar -cvf ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar \
            --exclude=".gi*" --exclude=".tr*" --exclude=".g_outdir" grass
          cd ${{ env.OUT_DIR }}
          gzip -9k ${{ env.GRASS }}.tar
          md5sum ${{ env.GRASS }}.tar.gz > ${{ env.GRASS }}.tar.gz.md5
          sha256sum ${{ env.GRASS }}.tar.gz > ${{ env.GRASS }}.tar.gz.sha256
          xz -9e ${{ env.GRASS }}.tar
          md5sum ${{ env.GRASS }}.tar.xz > ${{ env.GRASS }}.tar.xz.md5
          sha256sum ${{ env.GRASS }}.tar.xz > ${{ env.GRASS }}.tar.xz.sha256
      - name: Publish distribution to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.gz
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.gz.md5
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.gz.sha256
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.xz
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.xz.md5
              ${{ env.OUT_DIR }}/${{ env.GRASS }}.tar.xz.sha256
